# Generated by Django 2.1.10 on 2020-04-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В процессе', 'В процессе'), ('Почти готов', 'Почти готов'), ('Готов', 'Готов'), ('Отменен', 'Отменен'), ('Тестируется', 'Тестируется')], max_length=30),
        ),
    ]
