# Generated by Django 2.0.10 on 2020-05-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_repositorykey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='users',
        ),
        migrations.RemoveField(
            model_name='repositorykey',
            name='repository',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.DeleteModel(
            name='RepositoryKey',
        ),
    ]
