# Generated by Django 2.0.10 on 2020-05-17 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20200515_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Проблема', 'verbose_name_plural': 'Проблемы'},
        ),
        migrations.AlterModelOptions(
            name='solveproblem',
            options={'verbose_name': 'Решение проблемы', 'verbose_name_plural': 'Решение проблемы'},
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.TextField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='code',
            name='description',
            field=models.TextField(verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='code',
            name='name_problem',
            field=models.TextField(verbose_name='Название проблемы'),
        ),
        migrations.AlterField(
            model_name='code',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор проблемы'),
        ),
        migrations.AlterField(
            model_name='solveproblem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор решения'),
        ),
        migrations.AlterField(
            model_name='solveproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Code', verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='solveproblem',
            name='text',
            field=models.TextField(verbose_name='Решение'),
        ),
    ]
